colors:
  H1:
    1A.1: "#800080"
    1A.1.1: "#0099CC"
    1A.1.1.2: "#1182a8" # manual selection
    1A.1.1.3: "#176782" # manual selection
    1A.1.2: "#33FFFF"
    1A.1.3: "#6666FF"
    1A.1.4: "#6666FF"
    1A.2: "#CCCCFF"
    1A.2-3-like: "#FF33FF"
    1A.3: "#FF99FF"
    1A.3.1: "#8000FF"
    1A.3.2: "#FF33FF"
    1A.3.3: "#CC00CC"
    1A.3.3.1: "#004080"
    1A.3.3.2: "#330066"
    1A.3.3.3-c1: "#001E98"
    1A.3.3.3-c2: "#091f75" # manual selection
    1A.3.3.3-c3: "#0d1b52" # manual selection
    1A.3.3.3: "#3300FF"
    1A.4: "#FF33FF"
    1A.5.1: "#33FFFF"
    1A.5.2: "#6666FF"
    1A.5.3: "#004080"
    1B.1: "#FF9999"
    1B.1.1: "#CC0033"
    1B.1.2: "#FF66CC"
    1B.1.2.1: "#CC00CC"
    1B.1.2.2: "#FF3300"
    1B.1.2.3: "#FF9933"
    1B.2: "#996633"
    1B.2.1: "#CC9900"
    1B.2.2: "#C48945"
    1B.2.2.1: "#990066"
    1B.2.2.2: "#FF6666"
    1B.2.4: "#996633"
    1C.1: "#00FF00"
    1C.2: "#12AD2A"
    1C.2.X: "#12AD2A"
    1C.2.1: "#B9FF4D"
    1C.2.2: "#006600"
    1C.2.3: "#0FF591"
    1C.2.4: "#74C476"
    1C.2.5: "#24AE24"
    alpha: "#0099CC"	    #1A.1.1
    alpha-2: "#1182a8"      #1A.1.1.2
    alpha-del: "#176782"    #1A.1.1.3
    beta: "#CCCCFF"	        #1A.2
    gamma2: "#FF33FF"	    #1A.3.2
    pandemic: "#330066"	    #1A.3.3.2
    gamma-c1: "#001E98"	    #1A.3.3.3-c1
    gamma-c2: "#091f75"     #1A.3.3.3-c2
    gamma-c3: "#0d1b52"     #1A.3.3.3-c3
    gamma: "#3300FF"	    #1A.3.3.3
    LAIV: "#FF33FF"	        #1A.4
    delta2: "#CC9900"	    #1B.2.1
    delta1: "#C48945"	    #1B.2.2
    delta1a: "#990066"	    #1B.2.2.1
    delta1b: "#FF6666"	    #1B.2.2.2
#    No_data: "#EDF8B1"
  H3:
    1970.1: "#800080"
    1980.1: "#0099CC"
    1990.1: "#FF9999"
    1990.2: "#FFCC00"
    1990.3: "#FFFF00"
    1990.4: "#FF66CC"
    1990.4.1: "#CC00CC"
    1990.4.2: "#FF3300"
    1990.4.3: "#FF3300"
    1990.4.4: "#FF9933"
    1990.4.5: "#99FFFF"
    1990.4.6: "#3399FF"
    1990.4.7: "#CC9900"
    1990.4.8: "#66FF99"
    1990.4.9: "#FFB3E6"
    1990.4.10: "#9966FF"
    1990.4.11: "#CCFF66"
    1990.4.12: "#66CCFF"
    1990.4.a: "#CC00CC"
    1990.4.b1: "#00CCFF"
    1990.4.b2: "#00CCFF"
    1990.4.b: "#FF3300"
    1990.4.c: "#FF9933"
    1990.4.d: "#99FFFF"
    1990.4.e: "#3399FF"
    1990.4.f: "#CC9900"
    1990.4.g: "#66FF99"
    1990.4.h: "#FFB3E6"
    1990.4.i: "#9966FF"
    1990.4.j: "#CCFF66"
    1990.4.k: "#66CCFF"
    1990.5: "#990066"
    1990.6: "#0099CC"
    2000.1: "#00FF33"
    2000.2: "#00CCFF"
    2000.3: "#33CC99"
    2000.4: "#CCCC00"
    1990.7: "#CCCC00"
    2010.1: "#9900FF"
    2010.2: "#0E00D2"
    Other-Human-2010: "#CC0000"
    Other-Human-2020: "#999999"
    huVaccine: "#999999"
    LAIV: "#FF9999"	                #1990.1
    IV: "#FF66CC"	                #1990.4
    IV-A: "#CC00CC"     	        #1990.4.a
    IV-B1: "#00CCFF"	            #1990.4.b1
    IV-B2: "#00CCFF"	            #1990.4.b2
    IV-B: "#FF3300"	                #1990.4.b
    IV-C: "#FF9933"	                #1990.4.c
    IV-D: "#99FFFF"	                #1990.4.d
    IV-E: "#3399FF"	                #1990.4.e
    IV-F: "#CC9900"	                #1990.4.f
    IV-G: "#66FF99"	                #1990.4.g
    IV-H: "#FFB3E6"	                #1990.4.h
    IV-I: "#9966FF"	                #1990.4.i
    IV-K: "#66CCFF"	                #1990.4.k
    Human-like_2010.1: "#9900FF"	#2010.1
    Human-like_2010.2: "#0E00D2"	#2010.2
#    No_data: "#EDF8B1"
  N1:
    Classical: "#FEB24C"
    Pandemic: "#F03B20"
    Human_seasonal: "#BD2D2B"
    MN99: "#91BFDB"
    LAIV: "#91BFDB"
    N6: "#FF0000"
#    No_data: "#EDF881"
  N2:
    2002: "#FF42A4"
    2002A: "#008EFF"
    2002B: "#00CCFF"
    1998: "#007F00"
    1998A: "#00B122"
    1998B: "#00DC4F"
    2002A1: "#987FFF"
    2002A2: "#E049FF"
    2002B1: "#0059FF"
    2002B2: "#0093FF"
    02: "#FF42A4"
    02A: "#008EFF"
    02B: "#00CCFF"
    98: "#007F00"
    98A: "#00B122"
    98B: "#00DC4F"
    02A1: "#987FFF"
    02A2: "#E049FF"
    02B1: "#0059FF"
    02B2: "#0093FF"
    Human-to-swine_2016: "#1F38FF"
    Human-like_2010.2: "#996633"
    2016: "#996633"
    Human-like: "#969696"
    Human_N2: "#969696"
    TX98: "#FF9F02"
    LAIV: "#FF9F02"
    unknown: "#800000"
#    No_data: "#EDF8B1"
  PB2:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    LAIV: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  PB1:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    LAIV: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  PA:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    LAIV: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "###FF0000"
    unknown: "#800000"
  NP:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    LAIV: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  M:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    LAIV: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  NS:
    PDM: "#762A83"
    TRIG: "#C2A5CF"
    TX98: "#C7EAE5"
    LAIV: "#C7EAE5"
    Human-seasonal: "#969696"
    Human-seasonal_H3: "#969696"
    classicalSwine: "#FF0000"
    unknown: "#800000"
  Subtype:
    H1N1: "#D7191C"
    H1N2: "#FDAE61"
    H3: "#FFFFBF"
    H3N1: "#ABD9E9"
    H3N2: "#2C7FB8"
    mixed: "#E0F3F8"
    H4N6: "#FF0000"
