colors:
  Subtype:
    H1N1: "#D7191C"
    H1N2: "#FDAE61"
    H3: "#FFFFBF"
    H3N1: "#ABD9E9"
    H3N2: "#2C7FB8"
    mixed: "#E0F3F8"
    H4N6: "#FF0000"
  H1:
    1A.1: "#7B1FA2"
    1A.1.1: "#7B1FA2"
    alpha: "#7B1FA2"
    1A.1.1.1: "#4527A0"
    alpha-1: "#4527A0"
    1A.1.1.2: "#673AB7"
    alpha-2: "#673AB7"
    1A.1.1.3: "#E91E63"
    alpha-del: "#E91E63"
    1A.2: "#3949AB"
    beta: "#3949AB"
    1A.3.2: "#388E3C"
    gamma2: "#388E3C"
    1A.3.3.2: "#004D40"
    pdm: "#004D40"
    PDM: "#004D40"
    pandemic: "#004D40"
    Pandemic: "#004D40"
    1A.3.3.3: "#00897B"
    gamma: "#00897B"
    1A.3.3.3-c1: "#00ACC1"
    gamma-c1: "#00ACC1"
    1A.3.3.3-c2: "#29B6F6"
    gamma-c2: "#29B6F6"
    SPACE: "#1976D2"
    1A.3.3.3-c3: "#039BE5"
    gamma-c3: "#039BE5"
    1A.4: "#E57373"
    LAIV: "#E57373"
    1B.2.1: "#FF8F00"
    delta2: "#FF8F00"
    1B.2-like: "#FF8F00"
    1B.2.2: "#F57C00"
    delta1: "#F57C00"
    1B.2.2.1: "#EF6C00"
    delta1a: "#EF6C00"
    1B.2.2.2: "#E65100"
    delta1b: "#E65100"
    Other-Human-1B.2: "#546E7A"
    Other-Human: "#546E7A"
    other-human: "#546E7A"
  H3:
    1990.1: "#E57373"
    LAIV: "#E57373"
    SPACE: "#C62828"
    1990.4: "#1E88E5"
    C_IV: "#1E88E5"
    C IV: "#1E88E5"
    IV: "#1E88E5"
    1990.4.a: "#3F51B5"
    C_IVA: "#3F51B5"
    C IVA: "#3F51B5"
    IV-A: "#3F51B5"
    1990.4.b1: "#512DA8"
    C_IVB1: "#512DA8"
    C IVB1: "#512DA8"
    IV-B1: "#512DA8"
    1990.4.b2: "#BA68C8"
    C_IVB2: "#BA68C8"
    C IVB2: "#BA68C8"
    IV-B2: "#BA68C8"
    1990.4.c: "#006064"
    C_IVC: "#006064"
    C IVC: "#006064"
    IV-C: "#006064"
    1990.4.d: "#009688"
    C_IVD: "#009688"
    C IVD: "#009688"
    IV-D: "#009688"
    1990.4.e: "#00BCD4"
    C_IVE: "#00BCD4"
    C IVE: "#00BCD4"
    IV-E: "#00BCD4"
    1990.4.f: "#039BE5"
    C_IVF: "#039BE5"
    C IVF: "#039BE5"
    IV-F: "#039BE5"
    1990.4.g: "#0277BD"
    C_IVG: "#0277BD"
    C IVG: "#0277BD"
    IV-G: "#0277BD"
    1990.4.h: "#4DB6AC"
    C_IVH: "#4DB6AC"
    C IVH: "#4DB6AC"
    IV-H: "#4DB6AC"
    1990.4.i: "#66BB6A"
    C_IVI: "#66BB6A"
    C IVI: "#66BB6A"
    IV-I: "#66BB6A"
    1990.4.k: "#9E9D24"
    C_IVK: "#9E9D24"
    C IVK: "#9E9D24"
    IV-K: "#9E9D24"
    2010.1: "#E65100"
    2010_human-like: "#E65100"
    2010 human-like: "#E65100"
    2020.1: "#F57C00"
    2010.2: "#FFA726"
    2016_human-like: "#FFA726"
    2016 human-like: "#FFA726"
    2020.2: "#795548"
    Other-Human-2010: "#78909C"
    other-human-2010: "#78909C"
    Other-Human-2020: "#546E7A"
    other-human-2020: "#546E7A"
  N1:
    LAIV-Classical: "#E57373"
    LAIV: "#E57373"
    MN99: "#E57373"
    N1.C.1.1: "#E57373"
    SPACE: "#C62828"
    classicalSwine: "#64B5F6"
    Classical: "#64B5F6"
    N1.C: "#64B5F6"
    N1.C.1: "#AB47BC"
    N1.C.1.2: "#6A1B9A"
    N1.C.2: "#512DA8"
    N1.C.2.1: "#3F51B5"
    N1.C.3: "#1A237E"
    N1.C.3.1: "#2E7D32"
    N1.C.3.2: "#66BB6A"
    pdm: "#EF6C00"
    PDM: "#EF6C00"
    pandemic: "#EF6C00"
    Pandemic: "#EF6C00"
    N1.P: "#EF6C00"
  N2:
    LAIV-98: "#E57373"
    TX98: "#E57373"
    SPACE: "#C62828"
    1998: "#3F51B5"
    98: "#3F51B5"
    1998A: "#4527A0"
    98A: "#4527A0"
    1998B: "#5C6BC0"
    98B: "#5C6BC0"
    2002: "#00897B"
    02: "#00897B"
    2002A: "#33691E"
    02A: "#33691E"
    2002B: "#7CB342"
    02B: "#7CB342"
    2016: "#EF6C00"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
  internal:
    LAIV: "#E57373"
    TX98: "#C62828"
    avian: "#FB8C00"
    M-avian: "#FB8C00"
    M-avian-spillover: "#FB8C00"
    NP-avian: "#FB8C00"
    NP-avian-spillover: "#FB8C00"
    NS-avian: "#FB8C00"
    NS-avian-spillover: "#FB8C00"
    PA-avian: "#FB8C00"
    PA-avian-spillover: "#FB8C00"
    PB1-avian: "#FB8C00"
    PB1-avian-spillover: "#FB8C00"
    PB2-avian: "#FB8C00"
    TRIG: "#1E88E5"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
  PB2:
    LAIV: "#E57373"
    TX98: "#C62828"
    avian: "#FB8C00"
    M-avian: "#FB8C00"
    M-avian-spillover: "#FB8C00"
    NP-avian: "#FB8C00"
    NP-avian-spillover: "#FB8C00"
    NS-avian: "#FB8C00"
    NS-avian-spillover: "#FB8C00"
    PA-avian: "#FB8C00"
    PA-avian-spillover: "#FB8C00"
    PB1-avian: "#FB8C00"
    PB1-avian-spillover: "#FB8C00"
    PB2-avian: "#FB8C00"
    TRIG: "#1E88E5"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
  PB1:
    LAIV: "#E57373"
    TX98: "#C62828"
    avian: "#FB8C00"
    M-avian: "#FB8C00"
    M-avian-spillover: "#FB8C00"
    NP-avian: "#FB8C00"
    NP-avian-spillover: "#FB8C00"
    NS-avian: "#FB8C00"
    NS-avian-spillover: "#FB8C00"
    PA-avian: "#FB8C00"
    PA-avian-spillover: "#FB8C00"
    PB1-avian: "#FB8C00"
    PB1-avian-spillover: "#FB8C00"
    PB2-avian: "#FB8C00"
    TRIG: "#1E88E5"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
  PA:
    LAIV: "#E57373"
    TX98: "#C62828"
    avian: "#FB8C00"
    M-avian: "#FB8C00"
    M-avian-spillover: "#FB8C00"
    NP-avian: "#FB8C00"
    NP-avian-spillover: "#FB8C00"
    NS-avian: "#FB8C00"
    NS-avian-spillover: "#FB8C00"
    PA-avian: "#FB8C00"
    PA-avian-spillover: "#FB8C00"
    PB1-avian: "#FB8C00"
    PB1-avian-spillover: "#FB8C00"
    PB2-avian: "#FB8C00"
    TRIG: "#1E88E5"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
  NP:
    LAIV: "#E57373"
    TX98: "#C62828"
    avian: "#FB8C00"
    M-avian: "#FB8C00"
    M-avian-spillover: "#FB8C00"
    NP-avian: "#FB8C00"
    NP-avian-spillover: "#FB8C00"
    NS-avian: "#FB8C00"
    NS-avian-spillover: "#FB8C00"
    PA-avian: "#FB8C00"
    PA-avian-spillover: "#FB8C00"
    PB1-avian: "#FB8C00"
    PB1-avian-spillover: "#FB8C00"
    PB2-avian: "#FB8C00"
    TRIG: "#1E88E5"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
  M:
    LAIV: "#E57373"
    TX98: "#C62828"
    avian: "#FB8C00"
    M-avian: "#FB8C00"
    M-avian-spillover: "#FB8C00"
    NP-avian: "#FB8C00"
    NP-avian-spillover: "#FB8C00"
    NS-avian: "#FB8C00"
    NS-avian-spillover: "#FB8C00"
    PA-avian: "#FB8C00"
    PA-avian-spillover: "#FB8C00"
    PB1-avian: "#FB8C00"
    PB1-avian-spillover: "#FB8C00"
    PB2-avian: "#FB8C00"
    TRIG: "#1E88E5"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
  NS:
    LAIV: "#E57373"
    TX98: "#C62828"
    avian: "#FB8C00"
    M-avian: "#FB8C00"
    M-avian-spillover: "#FB8C00"
    NP-avian: "#FB8C00"
    NP-avian-spillover: "#FB8C00"
    NS-avian: "#FB8C00"
    NS-avian-spillover: "#FB8C00"
    PA-avian: "#FB8C00"
    PA-avian-spillover: "#FB8C00"
    PB1-avian: "#FB8C00"
    PB1-avian-spillover: "#FB8C00"
    PB2-avian: "#FB8C00"
    TRIG: "#1E88E5"
    humanSeasonal: "#546E7A"
    Human-seasonal: "#546E7A"
    Human-like: "#546E7A"
    pdm: "#7CB342"
    PDM: "#7CB342"
    pandemic: "#7CB342"
    Pandemic: "#7CB342"
